// Generated by Wrangler on Fri Sep 06 2024 19:21:34 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	BUCKET: R2Bucket;
	DB: D1Database;
}
